### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by foXaCe** [LordMike/MBW.BlueRiiot2MQTT#1]
hello very good idea and job.

how to install in home assistant ?
it possible to create addon ?

**Comment by LordMike** [comment]
You run it besides HASS. I prefer running this (and HASS) in docker.

**Comment by jimloki** [comment]
addons are just docker containers (https://developers.home-assistant.io/docs/hassio_addon_index/)

**Comment by foXaCe** [comment]
@jimloki  I don't have the competence to do this

**Comment by LordMike** [comment]
Oooh.. neat.. @jimloki ..

I'll have to take a look at what's needed to add them there .. I'm at work right now. But is there a store / repository where these are displayed, like f.ex. HACS has it?

**Comment by jimloki** [comment]
@LordMike You can do some local testing before publishing on the store. There's a community add-ons store or you can have your own add-on repositorie on github. Everything is explained in the link above.

@foXaCe Too bad. I would have done it if I had the competence also :)

**Comment by LordMike** [comment]
Yea, I just figured that out.. I've been able to install a local Hass.io install, as my own install is a HA Core setup (apparently).

**Comment by LordMike** [comment]
@foXaCe @jimloki give it a try

https://github.com/LordMike/hass-addons

**Comment by jimloki** [comment]
Waouh, that was fast!!! :)

I won't be able to try it because I don't have a Blue Connect device. I was just looking for information for a friend how wants to buy one and wanted to make sure Blue Connect was compatible with Home Assistant.

So it's up to @foXaCe to try it

**Comment by LordMike** [comment]
@jimloki it is. At least now it is. I was dissatisfied with the lack of support, a lot of the attempts out there will use Emails. As in, having Blue Riiot send an email on every measurement, and then having HASS parse those emails.

That's horrible.

Also, it only provides the values BR provides through emails, which without knowing exactly what it is - most likely won't be everything. From the API, it's possible to pull anything the App shows.

Tell your friend to install the app, and get a feel for it. That's what convinced me. The app works without the blue connect device, and will still let you report values for the pool, and provide recommendations on it. It's actually pretty neat.

**Comment by jimloki** [comment]
OK, I will.
Where do I put the username and password for the mqtt server?

**Comment by LordMike** [comment]
In the Hass.io setup, it will be:

```yaml
MQTT:
  Username: a
  Password: b
```

For regular docker, see the Readme.

**Comment by foXaCe** [comment]
This add-on is not available on your system.

**Comment by jimloki** [comment]
@foXaCe  To use this add-on, you need to add this address https://github.com/LordMike/hass-addons in the add-ons store in the repositories section, then you can add the add-on in your system.

@LordMike It still doesn't work with the username and password
`[2020-05-05 11:43:36+00:00 ERR] [MqttNet.MqttClient] Error while connecting with server.
[2020-05-05 11:43:36+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Reconnect failed
[2020-05-05 11:44:06+00:00 ERR] [MqttNet.MqttClient] Error while connecting with server.
[2020-05-05 11:44:06+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-05 11:44:06+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Reconnect failed
[2020-05-05 11:44:06+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30`

and in mosquitto log:
`1588679136: New connection from 172.30.32.1 on port 1883.
1588679136: Socket error on client <unknown>, disconnecting.`

Are you sure you're using these variables in your code?

**Comment by foXaCe** [comment]
@jimloki ok but not available for rpi4

![SharedScreenshot](https://user-images.githubusercontent.com/290678/81062983-47af3900-8ed7-11ea-950a-6d9162e7ee8e.jpg)

**Comment by LordMike** [comment]
@jimloki I've just found that Hass.io requires me to place all variables into the schema, in order for them to be used..

That's kinda crazy :O

**Comment by LordMike** [comment]
That configuration system is one of the stupidest I've ever worked with. 

Let me know if these changes work out, @jimloki

**Comment by jimloki** [comment]
Still doesn't work.
You should change the version in config.json each time, that way Home assistant will tell me when a new version is out. For now I don't know why I cannot install your latest version. I still got the same default config as the first time, no username and password for the MQTT server

**Comment by foXaCe** [comment]
[11:58:05 INF] Loading extra config file at /data/options.json
[2020-05-06 11:58:06+00:00 ERR] [MqttNet.MqttClient] Error while connecting with server.
[2020-05-06 11:58:06+00:00 WRN] [MqttNet.MqttClient] Error while waiting for internal tasks.
[2020-05-06 11:58:06+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-06 11:58:06+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30
[2020-05-06 11:58:06+00:00 INF] [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
[2020-05-06 11:58:06+00:00 INF] [Microsoft.Hosting.Lifetime] Hosting environment: Production
[2020-05-06 11:58:06+00:00 INF] [Microsoft.Hosting.Lifetime] Content root path: /app
[2020-05-06 11:58:09+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update
[2020-05-06 11:58:09+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while pushing updated data to MQTT
[2020-05-06 11:58:36+00:00 ERR] [MqttNet.MqttClient] Error while connecting with server.
[2020-05-06 11:58:36+00:00 WRN] [MqttNet.MqttClient] Error while waiting for internal tasks.
[2020-05-06 11:58:36+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-06 11:58:36+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30
[2020-05-06 11:58:36+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Reconnect failed

**Comment by jimloki** [comment]
I finally got it connected with my MQTT server. I can see an entity named  binary_sensor.blueriiot2mqtt_status. Unfortunately I cannot do more because I don't have a Blueriiot device.
@foXaCe could you please check if you got data coming in?

**Comment by LordMike** [comment]
@jimloki you can submit manual readings using the app.

**Comment by LordMike** [comment]
Ooh, right.. the version property.. I've been removing the feed and re-adding it while testing.

**Comment by foXaCe** [comment]
> I finally got it connected with my MQTT server. I can see an entity named binary_sensor.blueriiot2mqtt_status. Unfortunately I cannot do more because I don't have a Blueriiot device.


@jimloki  how to ?

**Comment by jimloki** [comment]
I've put some values in the application last night but still nothing in Home Assistant besides one entity (binary_sensor.blueriiot2mqtt_status)

![Capture d’écran du 2020-05-07 09-42-47](https://user-images.githubusercontent.com/34340550/81267709-2e2cff00-9047-11ea-8f2f-654c53a1fd5d.png)

Log:
`[07:36:34 INF] Loading extra config file at /data/options.json
[2020-05-07 07:36:36+00:00 INF] [MqttNet.MqttClient] Connected.
[2020-05-07 07:36:36+00:00 INF] [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
[2020-05-07 07:36:36+00:00 INF] [Microsoft.Hosting.Lifetime] Hosting environment: Production
[2020-05-07 07:36:36+00:00 INF] [Microsoft.Hosting.Lifetime] Content root path: /app
[2020-05-07 07:36:36+00:00 ERR] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] An error occurred while performing the update
[2020-05-07 07:36:37+00:00 INF] [MBW.BlueRiiot2MQTT.HASS.HassMqttSensor] Sent new values for BlueRiiot2MQTT Status to MQTT
[2020-05-07 07:37:20+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-07 07:37:20+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30
[2020-05-07 07:37:50+00:00 INF] [MqttNet.MqttClient] Connected.`

**Comment by jimloki** [comment]
It's working now, I thing... I put some values in the app as you said and now I can see more messages on the mqtt server and more entities in home assistant. Maybe I had a problem with my password in the addon, but I didn't have a warning about it.

I'm French by the way. Is it possible to get the messages in my language. I see that you have the option for the docker cli but not for the addon

**Comment by foXaCe** [comment]
@jimloki  I am French too. I would like to exchange with you so that you explain to me because me it does not work.

**Comment by jimloki** [comment]
Sorry @LordMike but I'll switch to French for this short message
@foXaCe Où veux-tu discuter? Je suis sur Discord (loki#2224)

**Comment by foXaCe** [comment]
ok works now


![image](https://user-images.githubusercontent.com/290678/81384866-9a286980-9112-11ea-9aa6-a4ee092a29aa.png)

**Comment by foXaCe** [comment]
please add this option

  Language: fr
  UpdateInterval: '00:00:00'

**Comment by barto64** [comment]
It looks pretty nice. I am planning to buy this Blue Connect device, but I have a doubt .... 

Do I need to buy the premium subscription for this component to work ?

I mean that because looking to the product web it looks like the basic version is only able to connect to the device using Bluethooth (Blue Connect Go), and for you to be able to access it through the internet you need to buy a more expensive one (Blue Connect)

**Comment by jimloki** [comment]
@barto64 I think you're right, unfortunately

**Comment by barto64** [comment]
> @barto64 I think you're right, unfortunately 

Thanks a lot for your prompt answer. I have already ordered the device. One of the toys I use is ESP32 cards which use BLE to talk lot of bluetooth devices, I will take a look first to see what I can get from there. Worst case scenario will be to buy the premium subscription and use your add-on.

**Comment by jimloki** [comment]
It's not my addon. I don't even have a blueriiot device. Like I said earlier, I was looking for information for a friend who wanted to buy one and wanted to make sure it could work with home assistant (I'm the one taking care of his installation). Now I'm not sure he will buy one because of this, plus he's starting to ask questions about blueriiot devices' reliability...

Hopefully someone will find a way to access the data by bluetooth, that would be the best option. May be 1technophile could help (see https://community.home-assistant.io/t/blue-connect-pool-measurements/118901/23 and https://github.com/1technophile/OpenMQTTGateway)

**Comment by LordMike** [comment]
@barto64 you do not _need_ the premium subscription. The API and app works without it. The premium subscription, afaik, only provides you with the Sigfox communication for the Blue Connect, so that it can make the ~20 readings a day.

Without the subscription, you're limited to doing manual bluetooth readings using your phone. It may be that the extender thingy doesn't need the subscription?..

That said. I much prefer the automatic-ness of it. :)

I've seen some threads related to making a bluetooth reader/implementation to make automated readings using a bluetooth dongle. Dunno how far that got though.

**Comment by LordMike** [comment]
I can add the language option to the Hass.io schema.

**Comment by LordMike** [comment]
@foXaCe it should be possible to specify the language now. I've also set the version of the Hass.io addon doc, to `0.1.0`.

**Comment by jimloki** [comment]
> Without the subscription, you're limited to doing manual bluetooth readings using your phone. It may be that the extender thingy doesn't need the subscription?..
> 

I think you're right about the extender. I read the manual and it doesn't mention a subscription. It's just a wifi bridge for the blue connect

**Comment by foXaCe** [comment]
@LordMike  thanks for language option

but

ERROR (SyncWorker_16) [supervisor.docker.interface] Can't install lordmike/blueriiot2mqtt-aarch64:0.1.0 -> 404 Client Error: Not Found ("manifest for lordmike/blueriiot2mqtt-aarch64:0.1.0 not found: manifest unknown: manifest unknown").

**Comment by jimloki** [comment]
Oups, maybe it's because of me. I told @LordMike to change the version in the config.json so that Home Assistant could warn us when an update is available. Now it's referencing a container that doesn't exist on the docket hub...

**Comment by foXaCe** [comment]
@jimloki do you have the same problem?

**Comment by jimloki** [comment]
yes

**Comment by foXaCe** [comment]
how to fix ?

**Comment by LordMike** [comment]
Oooh.. the version is the docker label... Right. God f...

It'll have to be `latest` for now. I'll have to do something with docker hubs builds to get versioned stuff.

**Comment by LordMike** [comment]
> 
> 
> > Without the subscription, you're limited to doing manual bluetooth readings using your phone. It may be that the extender thingy doesn't need the subscription?..
> 
> I think you're right about the extender. I read the manual and it doesn't mention a subscription. It's just a wifi bridge for the blue connect

Note that I don't know if there's any automation in this .. I could easily imagine that Blue Riiot would sell the extender, but not poll the Blue device automatically, unless you had the subscription.

I will say though, that I'm fairly confident the API I reversed, is able to request a measurement. So it would entirely be possible to code the automation within HASS.. (push to a specific topic every N minutes).

**Comment by barto64** [comment]
I am a bit confuse. Just for me to understand it.

How the BlueRiiot2MQTT talk to the Blue Connect Device? 

Does it use Bluetooth? Is it via WAN or LAN?

For what I read the Blue Connect use SigFox to be permanently connected to Internet and only need the WiFi extender in case of lack of SigFox coverage. A different thing is that w/o the subscription you do not get some benefits that the Premium subscription provides, like the 20 daily read, statistics, historical info,etc.

**Comment by jimloki** [comment]
BlueRiiot2MQTT talks to the cloud. The Blue connect device talks also to the cloud through sigfox or the wifi extender. You can also take measurements with your smartphone connected via Bluetooth to the Blue connect device. These measurements will then be sent to cloud.

That's what I  understand

**Comment by LordMike** [comment]
@barto64 -- jimloki is correct. I use the API that Blue Riiot provides for their app. I have not figured out how to talk to the blue device directly. I'm leaving that for others.

**Comment by barto64** [comment]
@LordMike , I am not especially interested on a Bluetooth based connection, my concern was that in absence of the Premium Subscription I could not integrate the device with my HA using your add-on. In any case I will find this out soon, I should get my device today. 

Is the add-on already back to work ? I saw some problems in the chat ....

**Comment by LordMike** [comment]
Well, it's been working for a while. There was a mishap with the version identifier in HASS, but that's been partly resolved. Turns out I need to tag my releases... :/

**Comment by jimloki** [comment]
The language option has no effect. The messages are still in english with "fr" in the config

**Comment by foXaCe** [comment]
i confirm, all languages rest en english

**Comment by LordMike** [comment]
Interesting. I haven't actually ever tested the language option, I just saw it being passed.

**Comment by barto64** [comment]
Well, I already got my device (Blue Connect Go), make the install of the add-on and it works like a sharm .... Great thanks to @LordMike for build this. I will now build a nice dashboard for my pool with all the sensors. I will share that if some one is interested. Every sensor provides lot of attributes than can help to build a very nice one.

I am now also more clear on some other stuff. There are two devices the cheap one which is white (Blue Connect Go, 200€) and the expensive one which is blue (Blue Connect Plus, €350). The Blue one comes with the premium suscription for life, meanwhile the White one needs to pay for that like 50€ per year. It means obviously the cheap one has the ability to communicate with the BlueRiiot cloud simply making that payment and it does not require any additional hardware. The Wifi extender is only required if your house is outside of SigFox coverage, which is not my case. In fact the app says my device talks to the Cloud periodically and provide a timestamp.

For White devices owners (200€ versus 350€), like me, the key would be to be able to simulate somehow in HA what the app does when you push the buttom to make a read via bluetooth. Depending on how the BlueRiiot guys designed their software it could be easy or difficult.  I will need sometime, that I do not normally have, to continue that line of investigation. Making HA to speak bluethoot is a 5€ problem with an ESP32 card which can be connected via ESPHOME integration. I have quite ESP32 working for different purposes using Wifi and Bluetooth combined, much bettter than a simple bluetooth dongle.

**Comment by jimloki** [comment]
@barto64 Thanks for all these information. To fully understand, did you take a one year subscription (at 50€) with it? That's how your white blue connect device uses sigfox to connect to the cloud? Because after reading Blueriiot website, I'm pretty sure you need a subscription to use sigfox

**Comment by barto64** [comment]
Nope. I did not buy the Premium Subscription. The fact that you do not have the subscription does not preclude the fact that your "bluthooth read" request result end up strored in the cloud and the nice @LordMike component can read it as you can from your mobile or tablet being in or out the bluetooth range of the device. This is how it happens. The reverse engineering of the API allows HA to simulate that it is your phone or table reading "last read" data from the cloud. This is the beauty of @LordMike work.

The ice in the cake would be to find the way of making HA able to simulate periodically the "bluetooth" read request. Thus, you would always have the info in the cloud and therefore in HA too fully updated, especially if you are not at home and cannot perform the "bluetooth" read request. 

In fact, I am planning to raise that to the BlueRiiot support, if you are not at home being able to make a "bluetooth" read request manually the device is basically useless.  I am sure they will tell me to buy the Premium Subscription though.

**Comment by jimloki** [comment]
OK. I misunderstood your previous comment. I thought you took a subscription because you said your "device talks to the cloud periodically and provide timestamps". I was already aware of the global operation.

Good luck with Blueriiot support. Like you said, they will tell you to buy a subscription :)

Communicate directly via bluetooth must be the best way

**Comment by foXaCe** [comment]
@barto64   thank you for the information.
can you make some screenshot to see how it looks on the dashboard ?

**Comment by barto64** [comment]
@jimloki , yes, in options, in the app, you can see a timestamp of last time the device read info using SigFox. A different thing is that info is not availabe if you do not pay.

@foXaCe , will need some time for that. Do not have too much free time.

**Comment by foXaCe** [comment]
I also use this to manage the pump

https://github.com/oncleben31/ha-pool_pump

**Comment by barto64** [comment]
> I also use this to manage the pump
> 
> https://github.com/oncleben31/ha-pool_pump

It looks nice. Thanks for sharing. I built mine on my own, I recall inspired in another one I use to watering my garden, long ago. I used packages rather than custom components; much easier if you want to make changes on your own and accomodate to your personal needs.

![Pump control](https://user-images.githubusercontent.com/47034221/81829023-c3922c80-953a-11ea-8da3-802dfd14ccf0.jpg)

**Comment by foXaCe** [comment]
very good, 
here is mine which is not finished yet

![image](https://user-images.githubusercontent.com/290678/81833076-8d0ae080-953f-11ea-873d-d7d1db5d4daa.png)

**Comment by barto64** [comment]
Really nice, will share mine when done.

**Comment by barto64** [comment]
@foXaCe , BTW, do you have the Premium Subscription or the Blue device ?

**Comment by foXaCe** [comment]
I'm buying the blue version, but I haven't received it yet.
for now I enter the information manually in the application.

**Comment by barto64** [comment]
A first prototype of how the gauges will look like
![3A7CB206-9BEF-4354-A85F-0F27328D895B](https://user-images.githubusercontent.com/47034221/81980694-6035f680-962f-11ea-9362-6ab0c7098750.jpeg)

**Comment by jimloki** [comment]
Nice!

**Comment by LordMike** [comment]
All neat. I haven't had a chance to look at the language thing, yet. 

EDIT: I found a bug in the language thingy, for guidance stuff. It's fixed in `0.1.1`

**Comment by foXaCe** [comment]
![image](https://user-images.githubusercontent.com/290678/82010962-e8d68600-9673-11ea-9ea0-6fc9b99cba22.png)

work now
very good thank you

**Comment by barto64** [comment]
The final look and feel ....
![piscina](https://user-images.githubusercontent.com/47034221/82141047-93e16e00-9833-11ea-8ee3-3bec07d178c9.jpg)

**Comment by foXaCe** [comment]
very beautiful
good job

**Comment by LordMike** [comment]
@barto64  are you using the `okmin`, `okmax`, `warninglow` and `warninghigh` attributes of the sensors, for your guages? .. That would be exactly why I added those attributes :)

**Comment by barto64** [comment]
Yes, indeed, they are really usefull. They are used to set the colors of the gauge, okmin and okmax provides the "green" area of the gauge, warning low and high provides the "red" area, and in betwenn the area is "yellow".

**Comment by LordMike** [comment]
That's awesome. 

Note that you can tweak those values within the Blue Riiot app. It's in the configuration of the pool somewhere.. :)

**Comment by barto64** [comment]
Hey, periodically, I see in the integration log quite a few errors of disconnexion and reconnection. Is this expected ? Is it a local issue of my Rpi4 or a BlueRiiot server issue ?

[2020-05-18 15:48:52+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-18 15:48:52+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30
[2020-05-18 15:49:22+00:00 INF] [MqttNet.MqttClient] Connected.
[2020-05-18 15:50:52+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-18 15:50:52+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30
[2020-05-18 15:51:22+00:00 INF] [MqttNet.MqttClient] Connected.
[2020-05-18 15:55:52+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-18 15:55:52+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30
[2020-05-18 15:56:22+00:00 INF] [MqttNet.MqttClient] Connected.
[2020-05-18 15:56:56+00:00 INF] [MqttNet.MqttClient] Disconnected.
[2020-05-18 15:56:56+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.MqttConnectionService] Server disconnected, attempting reconnect in 00:00:30
[2020-05-18 15:57:26+00:00 INF] [MqttNet.MqttClient] Connected.

**Comment by LordMike** [comment]
You should create new issues for new problems :)
