### ISSUE TITLE
Add command to force poll/sync

### ISSUE THREAD

**Issue by LordMike** [LordMike/MBW.BlueRiiot2MQTT#16]
Following #11 - add an MQTT command to force a poll.

**Comment by ggggh** [comment]
Haven't been able to get this one working - seems command is not received in app (using latest docker image).  
Will any message do? what prefix is taken, is it the HASS__BlueRiiotPrefix ?  The verbose log doesn´t seem to show it subscribing to any topic

**Comment by LordMike** [comment]
Oh, I also changed the config. Damn.. Will need to note that.

With default settings, it should be `blueriiot/commands/force_sync`. The logs should indicate that a force sync was started.

Here is a screenshot of the logs after I push (any) message to that topic. 

![image](https://user-images.githubusercontent.com/1027111/89903489-fe623a00-dbe7-11ea-9ecf-46f7f38a7bb7.png)

**Comment by LordMike** [comment]
@ggggh sorry about that. I've updated the readme for the new config:

https://github.com/LordMike/MBW.BlueRiiot2MQTT#environment-variables

**Comment by ggggh** [comment]
No problem!  Had tried with that one, and also tried again with and without setting HASS__TopicPrefix, but can't get a response on the application log, even in verbose.  Sending my message to: blueriiot/commands/force_sync

**Comment by LordMike** [comment]
And you're running the `latest` or `dev` tags?

**Comment by LordMike** [comment]
In verbose logging, you should also see a message from `MqttCommandService` indicating that it's `Subscribing to ...` topics..

**Comment by ggggh** [comment]
tried both latest and dev; can't see a message for "Subscribing" on the container logs, or from the MqttCommandService

**Comment by LordMike** [comment]
That's odd.. Uhm. What's your image id?

> docker image ls lordmike/blueriiot2mqtt:latest

Should be `d3f36d68f052`

Else I'll have to add more debug logs to the commands to see what's up.

**Comment by ggggh** [comment]
Apologies - seems it was some issue on mi docker compose caching an old image.
Image id still isn't the same as yours, but the force synch is working great now anyway :)

**Comment by LordMike** [comment]
Oh thank god. Yea, the `dev` moved as I pushed the readme change. 

But great stuff... :)
