### ISSUE TITLE
Ignore BLE measurements when calculating next poll time

### ISSUE THREAD

**Issue by LordMike** [LordMike/MBW.BlueRiiot2MQTT#20]
When a bluetooth measurement is made, it's likely that that measurement time is used as a basis for the next poll - but if the Blue device does not take this into account, one poll interval will be out of order (we'll poll later than anticipated)

Should be testable by making a Bluetooth measurement moments before a scheduled measurement, and see if data arrived by sigfox shortly after.

**Comment by ggggh** [comment]
Just did a check (simplified numbers below):

- Scheduled measurement taken at time 13:00
- Next measurement was scheduled at time: 14:00
- Did a bluetooth-triggered measurement at 13:30, so BlueRiiot2MQTT rescheduled next active time to 14:30
- Did a bluetooth-triggered measurement at 14:01, and there was data available from a 14:00 upload.

Therefore my assessment is the bluetooth measurement did not modify the next poll plan and we should not extend the poll interval when a forced synch is triggered

**Comment by LordMike** [comment]
Awesome. I should be able to modify the logic such that BLE measurements are not used for time calculation.

Thanks :)
