### ISSUE TITLE
Sensor status as _2 or _status

### ISSUE THREAD

**Issue by gllmlbrt** [LordMike/MBW.BlueRiiot2MQTT#22]
Hi, 

I use the app with auto discovery in Hass with an eclipse docker image for mqtt server. Hass, the app (compose) and the mqtt server are ran on "container station" docker on a Qnap NAS.

The sensor providing the reading is accompanied with a status sensor. Sometimes the second status sensor is differentiated with a _2 sometimes with a "_status" for OK, Warning or Bad.
See screenshot for sensor.pool_conductivity(_2) and sensor.pool_cyuranic_acid(_status).
![Capture](https://user-images.githubusercontent.com/58825251/91167320-1059d780-e6d4-11ea-94fb-aee5cf30647d.PNG)

I suppose it should be consistent as a minimum, and I suggest it is consistently
 marked as _status.

**Comment by LordMike** [comment]
I was just about to explain how to clear MQTT topics, but you're right. I've missed a "_status" suffix :O

Nice catch!

**Comment by LordMike** [comment]
Fixed in 9486b254521afc10a40062a7861679a7e4e5bd0c

To resolve it on your (and my) end, I suspect we'll have to clear the MQTT discovery topics, and have them be recreated.

**Comment by Nordicfastware** [comment]
THanks, yes we will have to delete the device first.
I added a comment in code line for typo: "ORP status" instead of "OR statusP"

**Comment by LordMike** [comment]
@Nordicfastware I'm closing this as I suspect v0.8 resolved this for you as it did for me. :)
