### ISSUE TITLE
[Question] How change the default MQTT prefix / disable HASS topic

### ISSUE THREAD

**Issue by NemoN** [LordMike/MBW.BlueRiiot2MQTT#23]
- For me the default prefix is "blueriiot". Is it possible to change that via docker-compose setting file?
- Is it possible to disable the "homeassistant" topic? (for all users that are not using HASS...

**Comment by LordMike** [comment]
On the readme some of the settings you can set are described.

In your case, it would be:

* Set the environment variable `HASS__TopicPrefix` to `my-blueriiot` (or whatever you'd like)

Right now, the HASS integration cannot be disabled ... buut, I could probably make that a thing.

**Comment by NemoN** [comment]
Missed the HASS__TopicPrefix completely. I will give them a try 👍

**Comment by LordMike** [comment]
A new `dev` image will soon have the ability to completely stop sending HASS discovery documents.

**Comment by NemoN** [comment]
Just tested the new image:
- disable HASS discovery topic: works 👍 
- change HASS__TopicPrefix: works 👍
