### ISSUE TITLE
Get Next poll time

### ISSUE THREAD

**Issue by ghost** [LordMike/MBW.BlueRiiot2MQTT#26]
Is it possible to get Time information when Next Poll Time will be done?

**Comment by LordMike** [comment]
Uh, sure. I think so.

**Comment by LordMike** [comment]
I can place an attribute on the operational sensor for each pool - or would you prefer a new sensor?

Unless you're not using HASS, then the same question - but with topics instead?

**Comment by ghost** [comment]
Im using HASS.  Hmm.. I dont really know but I think it should be connected to the operational sensor, but I need the updates even if BlueRiiot__ReportUnchangedValues = false.

**Comment by LordMike** [comment]
Sure. The operational sensor is always updated. I'll add an attribute for starters.

**Comment by LordMike** [comment]
It's in 0.9.1 shortly.
