### ISSUE TITLE
Add to [-HACS-] edit: HASSIO Addons ?

### ISSUE THREAD

**Issue by shanelord01** [LordMike/MBW.BlueRiiot2MQTT#27]
Hi,

I'm trying to streamline my installs as much as possible - just wondering if this could be added to HACS to make the install easier?

https://hacs.xyz/

Thanks,
Shane.

**Comment by shanelord01** [comment]
I do want to say - was quite easy to get up and running in Docker on Synology. Already have MQTT server setup in HASS.IO so just had to setup key environment variables in the Synology Docker UI and it worked first go.

Thanks.

**Comment by LordMike** [comment]
You can add docker stuff to HACS?

**Comment by shanelord01** [comment]
> You can add docker stuff to HACS?

Hmmm - you're correct - so sorry I meant Add-on in HASSIO addons. And I'm an idiot - just found https://github.com/LordMike/hass-addons

Didn't see this in the instructions so had no idea you had a repository :)

**Comment by LordMike** [comment]
... maaaybe I should put a link to that repo .. :P
