### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by magicmike2452** [LordMike/MBW.BlueRiiot2MQTT#30]
Hi, 
I was getting this error too. 

I restored my homeassitant, not knowing that there could have been an issue. Anyway, installed 0.9.2 and it connects OK. But I don't get any sensors coming in. Maybe its my installation :/

[2020-12-10 02:16:47+00:00 INF] [MBW.BlueRiiot2MQTT.Service.BlueRiiotMqttService] Discovered new pool, 'Stanny Pool'
[2020-12-10 02:16:52+00:00 INF] [MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater] New data ready for pool 'Stanny Pool' at 12/10/2020 02:19:35 (interval 01:12:00). Waiting 00:02:42.8398104
[2020-12-10 02:16:52+00:00 INF] [MBW.HassMQTT.HassMqttManager] Pushed 20 discovery documents, 19 values and 20 attribute changes
[2020-12-10 02:19:39+00:00 INF] [MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater] New data ready for pool 'Stanny Pool' at 12/10/2020 03:30:42 (interval 01:12:00). Waiting 01:11:02.3151702
[2020-12-10 02:19:39+00:00 INF] [MBW.HassMQTT.HassMqttManager] Pushed 0 discovery documents, 1 values and 2 attribute changes
[2020-12-10 03:30:47+00:00 WRN] [MBW.BlueRiiot2MQTT.Service.PoolUpdater.SingleBlueRiiotPoolUpdater] There were 1 consecutive updates without new data for 'Stanny Pool', setting next run to be 12/10/2020 03:31:47, waiting 00:01:00

_Originally posted by @colesealeaf in https://github.com/LordMike/MBW.BlueRiiot2MQTT/issues/29#issuecomment-742280830_

Getting the same issue, must be the configuration between Mqtt and the add-on. How have others set it up?

Appreciate any assistance

**Comment by LordMike** [comment]
Was this resolved already?

To verify all kinds of MQTT stuff, I'd recommend the MQTT Explorer tool.

**Comment by colesealeaf** [comment]
Thanks Mike, much appreciated.

I am having a crash course in MQTT explorer now :)

Everything seems fine, blueriiot connects to MQTT ok. Homeassistant is connected to MQTT. Strange one.

I'll see if I can figure out how to enable the logging.

**Update:** MQTT explorer is not listing anything except sys$ and Homeassistant, so even though blueriiot is saying its connected, its not. Thank you for the guidance. I would say this is nothing to do with the update.

**Update 2** Fixed! Thank you for the tip with MQTT explorer, helped me a lot, even though everything looked connected it actually wasn't. Removed MQTT, re installed and its working again now.

**Comment by LordMike** [comment]
That's cool.. :)

But I was really referring to @magicmike2452 .. who I now see was different than the person I originally thought had an issue. This repo is getting popular :D As for MQTT Explorer - yea, it really gives some insight into what's actually happening on the MQTT side, so most issues can be troubleshooted that way. Once you're familiar with it, you can also post new messages onto topics of your choosing to troubleshoot HASS issues.

So, @magicmike2452 did you get this resolved? :)

**Comment by magicmike2452** [comment]
Apologies for the late response - tried out MQTT Explorer with still minimal luck. Does the addon work properly even with MQTT configs set to anonymous? I seem to run into issues when setting up login access for MQTT but will try again, must be doing something wrong in the configs.

Here's what my MQTT explorer looks like - seems to have made the sensors and now they have disappeared? Can't get it back, probably had the correct config at one point, now broke it again. Perhaps I need a dumbed down guide

Appreciate any assistance, cheers.
![image](https://user-images.githubusercontent.com/75776909/102728967-a94ae780-4382-11eb-8b0a-e7f30f311e19.png)

**Comment by LordMike** [comment]
Try leaving MQTT explorer open. As you can see, the messages you're seeing are "Retained". This means the MQTT server keeps them stored and sends them to new subscribers. So to see if BR2M really works, you need to restart it while keeping MQTT Explorer open. If all the topics flash, then that means a new message was pushed through it. You can also see in the history tab (right side, below the data) if any new messages arrive, as well as what they contained.

If BR2M is pushing through data, then the issue is elsewhere.
