### ISSUE TITLE
Sensors Unavailable after update to 0.9.2

### ISSUE THREAD

**Issue by cdk222** [LordMike/MBW.BlueRiiot2MQTT#31]
Did the MQTT topics change in the latest update. HASS addon was working fine until I updated to 0.9.2 and now all of my sensors are showing as unavailable.  If I search through my entity list they are no longer there. They also do not appear to be updating in MQTT explorer. I haven't changed any settings between upgrades.

How do I roll back to an old version?

**Comment by LordMike** [comment]
Hmm. There should be no changes, what was the last version you used before this .. 0.9.1?

I shouldn't have changed _any_ topics for a long time. Verify:

* That the log output from BR2M doesn't indicate errors
* Use MQTT explorer to see if the topics are updated as expected

To run an old version, you need to use the tag for that version. On [the docker hub](https://hub.docker.com/r/lordmike/blueriiot2mqtt/tags?page=1&ordering=last_updated), you can see the available tags. There is one named `v0.9.1` f.ex.

**Comment by cdk222** [comment]
Thanks for replying: I was using 0.9.0

I uninstalled the addon, deleted the topics from MQTT and re-installed. Came back up straight away and is now working.

Been one of those days, Pool pump packed in, the pipe saddle for the Blueriiot cracked when I was tightening it and then the addon stopped working. I hate pools!!! lol

Thanks

**Comment by LordMike** [comment]
I'm actually curious as to _what_ happened. If you update to 0.9.2 again, does it fail again?

There was _a_ change in one topic a while back, but shouldn't be anywhere near 0.9+.. Can't remember when.

**Comment by cdk222** [comment]
After the uninstall - i reinstalled 0.9.2 and it worked fine. 

I did notice an increase in the default config settings (almost double) on the new version in comparison to 0.9.0.....i did look at the config before the uninstall hence why I noticed the increase. Maybe the fact that the update just rolled over my (lesser) config, potentially caused the issue???

**Comment by LordMike** [comment]
Huh - that would be bad.. Definitely bad. I recently exposed more configs through the Hassio addons, per request.

**Comment by cdk222** [comment]
........really appreciate the work you have put in on this Mike. Its a great HASS addon.
