### ISSUE TITLE
Where do I find BlueRiiot username and password

### ISSUE THREAD

**Issue by TheGreatHorla** [LordMike/MBW.BlueRiiot2MQTT#33]
I'm feeling stupid today: Where would I find a BlueRiiot username and password? I have the Blueriiot app installed but in account settings I only find my name and e-mail?

**Comment by LordMike** [comment]
I believe my username is my email, and the password is my account password..

Can't help you with your password :)

**Comment by TheGreatHorla** [comment]
ok, now I found it. You can choose logoff in the app. Tried a few of my 'standard' passwords and logged in without problems. Thx.
