### ISSUE TITLE
sensor names and language

### ISSUE THREAD

**Issue by TheGreatHorla** [LordMike/MBW.BlueRiiot2MQTT#34]
Is there a list of al sensors which are configured when you install and configure it? I found sensors for forecast, pool update status etc but not the usefull sensors like temperature, ph, alkalinity, etc. Or is this because my sensor has the status asleep (It's still a little bit chilly here in Belgium)?

Also, which language parameters can we use? The only one which seems to work is 'en'. nl and fr doesn't change anything in the sensor language. I installed it as a HASSIO add-on.

**Comment by LordMike** [comment]
I don't maintain a list of all sensors, but they should appear automatically. You're likely correct that as long as the BR is asleep, I won't be incorporating it.. Once it comes online, it will appear.

My own BR is also in storage, as we haven't even hit 10C* yet :P

**Comment by LordMike** [comment]
I just double checked.. As I can't know if your BR device supports f.ex. pH, alkalinity, orp, etc.. I've made the code such that it reports sensors for any value that has a measurement. The [exact code is here](https://github.com/LordMike/MBW.BlueRiiot2MQTT/blob/2381d4862924565222ccf072df863f84206c3f09/MBW.BlueRiiot2MQTT/Features/Pool/PoolMeasurementFeature.cs#L34-L38) - BR provides an "Expired" indication, (a way to know if the BR hasn't reported in on time) - which I use. Your device likely has measurements .. from last year, which are all expired.

They'll appear when you wake the device :).

**Comment by LordMike** [comment]
> Also, which language parameters can we use? The only one which seems to work is 'en'. nl and fr doesn't change anything in the sensor language. I installed it as a HASSIO add-on.

Language changes the suggestions that BR provides - the sensor names are not affected. When your device wakes up, it will receive suggestions like "increase pH by N".. This text changes given the language you choose.

**Comment by TheGreatHorla** [comment]
Fast response! It's been a few months (I used a monthly subscription last year because it's cheaper than a full year) so I didn't remember if dutch was supported or not ;-). 

Thx for this integration with HA, it will do wonders for the WAF!
