### ISSUE TITLE
Got not all sensors

### ISSUE THREAD

**Issue by PuschRo** [LordMike/MBW.BlueRiiot2MQTT#38]
Hello,
i´m installed the homeassistant plugin.
But i got only 5 sensors looks like this
![image](https://user-images.githubusercontent.com/75539173/113432496-c3628000-93dd-11eb-974c-4026ea9cf9b8.png)

What shall i do

**Comment by LordMike** [comment]
Are there any recent readings from the Blue device?

Related: #34

**Comment by PuschRo** [comment]
Not shure,
it can read out my poolname but no changes else. The battery sensor is alway on 10 percent, thats not true.....
see my attachements:

![IMG_1150](https://user-images.githubusercontent.com/75539173/113681128-e92fa380-96c1-11eb-834b-e451100f6c4a.jpg)
![IMG_1151](https://user-images.githubusercontent.com/75539173/113681135-ec2a9400-96c1-11eb-8828-96f124b02c62.jpg)
![IMG_1152](https://user-images.githubusercontent.com/75539173/113681146-ee8cee00-96c1-11eb-99f4-17d503412fca.jpg)

**Comment by LordMike** [comment]
The log you showed, "pushed 18 discovery documents" indicates that 18 sensors were pushed. You're only seeing 5 there - so either HASS rejected them, or you're just not seeing them.

Could you try opening your `Entities` page (http://your-hass/config/entities) and searching for `puschel` ?

**Comment by LordMike** [comment]
As for the battery.. I don't actually know _how_ to read the battery.. I found a value that seems like a "low battery .. yes / no" - which I've translated to "no => 100%" and "yes => 10%".

**Comment by PuschRo** [comment]
Oh my gosh, i searched only for blue........    The enities are all there...... Sorry
Do i need a premium account to get all the entitie - informations?

**Comment by LordMike** [comment]
Awesome :)

I don't think so. The info is the same, no matter what account you have.

But - the premium subscription gives you automatic measurements, f.ex. over Sigfox.

**Comment by PuschRo** [comment]
Thank you so much :-)
