### ISSUE TITLE
Schedule "no reading" timer

### ISSUE THREAD

**Issue by dodg3r** [LordMike/MBW.BlueRiiot2MQTT#41]
Hi.

I don´t know if this is possible or if it´s even nesesary.

I´m using pump schedule and between 21:00-08:00 there is no readings from blue connect.
Can we have an option in config so we can pause the readings between a certain time?

**Comment by LordMike** [comment]
What happens right now?

Are there any measurements made in this period, or does BR2MQTT log something like `There were N consecutive updates without new data for ..` ?

**Comment by dodg3r** [comment]
Hi.

Thats what I thought but now when you changed the code to listen to "last_measure_message_gateway" that timestamp changes even if blue connect doesnt do a reading.

So I close this.
