### ISSUE TITLE
No entities under MQTT Integration

### ISSUE THREAD

**Issue by Marra74** [LordMike/MBW.BlueRiiot2MQTT#49]
Hi!

At first, thank you LordMike for your good work with this integration.
I have configured it all and tryed to read and follow the documentation. 

The problem i have is that the "MQTT Integration" does not show any entities.?

1. In the log for the MQTT Server, i can see that blueriiot2mqtt i s connecting.
2. In the BlueriiotMQTT Addon i can see clearly in the log that it find the pool and data for it.
3. I can see 3 disabled entities under "Hass Entities". (Have tryed to enable them)

But in the MQTT integration there is no entities?
Do i need to set some entry in the Configuration.yaml?
In the MQTT Integration configuration is it the "MQTT Server" hostname i should use here?
I attaching the logs...

Best regards!

![dump mqttsrv](https://user-images.githubusercontent.com/32649431/119834872-9e334f00-bf00-11eb-9d54-494769bc4dd4.png)
![dump br](https://user-images.githubusercontent.com/32649431/119834904-a3909980-bf00-11eb-8c68-7ef1ce516a63.png)
![hass entities](https://user-images.githubusercontent.com/32649431/119834930-ab503e00-bf00-11eb-8c7b-b60bf4b31f32.png)
![dump mqtt-int](https://user-images.githubusercontent.com/32649431/119834952-af7c5b80-bf00-11eb-9925-a56769de381b.png)

**Comment by dodg3r** [comment]
Hi.

In my mqtt server I can se 3 devices:

![image](https://user-images.githubusercontent.com/46417555/119882242-7a86fd80-bf2e-11eb-853b-03bbacdfba0b.png)

All of them is for blueconnect.

Did you follow the mqtt guide and created a mqtt user in hass?
Do you se in the log that hass logs in?

![image](https://user-images.githubusercontent.com/46417555/119882494-c46fe380-bf2e-11eb-8959-44f20dc02cdb.png)

**Comment by dodg3r** [comment]
Or maybe you havent enabled this i systemoption under integration/mqtt

![image](https://user-images.githubusercontent.com/46417555/119882740-0731bb80-bf2f-11eb-9a81-81c3377cd192.png)

**Comment by Marra74** [comment]
Sorry i had the wrong MQTT addon installed. I Had the MQTT Server & Web client installed. When i Uninstaled and installed MQTT Broker Addon the integration now shows entities. :)

Thank you for your help!

**Comment by dodg3r** [comment]
Glad you solved it. 

I think you can close this issue then.

**Comment by Marra74** [comment]
Solved! 👍

**Comment by LordMike** [comment]
Thanks @dodg3r ! :)
