### ISSUE TITLE
Add support for salinity

### ISSUE THREAD

**Issue by foXaCe** [LordMike/MBW.BlueRiiot2MQTT#5]
I don't have salinity going up in mqtt

![image](https://user-images.githubusercontent.com/290678/82318386-0e46f500-99d0-11ea-9147-7f08da964adf.png)

![image](https://user-images.githubusercontent.com/290678/82318553-57974480-99d0-11ea-9dbe-242834f75c05.png)

**Comment by LordMike** [comment]
Ooh.. Neat. I wonder what that's called.

**Comment by LordMike** [comment]
I have pushed `0.1.3`, the docker images should be there soon.

**Comment by foXaCe** [comment]
great, thank you. congratulations for the work.
riio would have to add alkalinity, to make this device complete.
you have earned a right to swim in my pool.


![image](https://user-images.githubusercontent.com/290678/82736116-6ca10a00-9d27-11ea-8fc8-1fb8d8ba48fb.png)

**Comment by LordMike** [comment]
That's awesome - I'll see when France opens up :)
