### ISSUE TITLE
Blue Connect devide versions  

### ISSUE THREAD

**Issue by Wichow1** [LordMike/MBW.BlueRiiot2MQTT#55]
Hi, 

Does the integration is compatible with Blueriiot "Blue Connect Go" or only with "Blue Connect Plus" ?
The Go version seems to be BT only...
Thanks

**Comment by LordMike** [comment]
This should be compatible with "all" those versions... But you won't get the regular readings when using bluetooth-only versions.

This app communicates with the same API that the Blue Riiot app uses. So the data you can see in the app, is also available through this. As mentioned, bluetooth only devices will need you to perform readings manually - we have #21 for the wifi box you can buy, and discussion on simulating the bluetooth reading can be found on the Home Assistant forums.

**Comment by Wichow1** [comment]
Ok, Thank you Mike!
