### ISSUE TITLE
Request: Support Domoticz

### ISSUE THREAD

**Issue by DAVIZINH0** [LordMike/MBW.BlueRiiot2MQTT#58]
Hello!,
Sorry if this is not the correct method to comunicate with you.
I see your docker and is excelent! it works fine with hass.io plugin.
This is very usefull for me and my blueriiot device. THANKS A LOT!

i have a suggestion, and i dont know i you consider it .
Many people like me, using domoticz and not home assistant.
Do you consider make a option to publish mqtt that domoticz can use?

thanks a lot for your work!

**Comment by LordMike** [comment]
If possible, could you locate the docs on this integration, and possibly some small examples?

Also - I have no idea how Domoticz maps to HASS, like devices vs. entities.. or if its expected to have one value per "thing" or multiple values..

**Comment by DAVIZINH0** [comment]
Hello and thanks for your reply!

with domoticz exist 2 posibilities:
1.- make a plugin for domoticz. i dont know how :-(
2.- inject the info by mqtt

i will explain the second posibility because is easy for me to expain :-)

In domoticz i will create a hardware device (dummy type). After this I create al dummy sensor i need. Example:
- Hardware= blueriiotMQTT
       - Device 1: ph value
       - Device 2: temperature
       - Device 3: Clore
       - Device 4: etc....
(when i create a dummy device its easy to configure the type (units))

After this, each device have a "idx" device. this is a numeric identifier: Example Device 1: idx 201. Device 2: idx: 202

In all of this you dont need to do something. If you make this compatible i will make a tutorial for your github expain all the steps to create all the dummy devices. no problem for me

now, how domoticz obtain the information of the mqtt?. if i want to push a value to idx 201 i will use this command:
mosquitto_pub -h localhost -m '{ "idx" : 1, "nvalue" : 0, "svalue" : "25.0" }' -t 'domoticz/in'

localhost is the ip of the mqtt broker
the "1" is de value of idx i will update
the nvalue or svalue is the value i will to update. depend of type of sensor use one o other (i will tell you when i create the dummys)

for the exaple (ph value = 7.2 and idx = 201) the comand is this:
mosquitto_pub -h 192.168.1.2 -m '{ "idx" : 201, "nvalue" : 0, "svalue" : "7.2" }' -t 'domoticz/in'

This is a long post, hahaha. english is not my natural languaje, i hope i can explain correctly!

and now, how to implement this. I have a idea but i dont know if is the best:
- a variable "domoticz enable" YES
- a file in a container folder (persistent maped) with the list of sensors and the idx of each. The user will update this file with his own idx for each device.

whats your opinion? its posible? its to hard?

THANKS A LOT AGAIN!!!!

**Comment by DAVIZINH0** [comment]
hello again.
Now domoticz are implementing a autodiscover method to mqtt devices.
I set the topic to "pool" and setup this topic in the autodiscover in domoticz. this works. not perfect, but works :-)

**Comment by LordMike** [comment]
Oh great. I was just a out to report back that I won't be able to find the time to make a domoticz-specific implementation .. 

I can tweak the current setup if Domoticz' new HASS-ish support is lacking some specific feature or interprets a new property ... :)
