### ISSUE TITLE
Leveraging latest Home Assistant developments related to statistics

### ISSUE THREAD

**Issue by barto64** [LordMike/MBW.BlueRiiot2MQTT#61]
First of all, great thanks for this integration, it is wonderful and one of my favourites and by far more used and usefull.

Would it be possible to enrich the sensors created for this integration in order to leverage the new statistics features of HA

I leave you this link as reference:

In here https://www.home-assistant.io/more-info/statistics/ you can read the below:

Open an issue with the author of the integration and link them to 
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by LordMike** [comment]
Which metrics do you think could qualify for Statistics?

I'm thinking all the measurement values, like temperature, pH, ..

**Comment by barto64** [comment]
Fully agree. Temperature, ph, oro, etc.

**Comment by LordMike** [comment]
Would they have to be new sensors, or retask the existing ones?

They don't have any class today, so it wouldn't change anything, but will they continue as sensors today if they get one of those classes?

I'm updating my models library, I've noticed I'm behind on changes. Once that's done, I can utilize it here.

**Comment by barto64** [comment]
I do believe you only need to add the new property to tHe existing sensors. At least that is what I understand by reading the documentation. 

But in any case worthy to make some testing.

**Comment by barto64** [comment]
Making the new property state_class as "measurement" represents what, at the end of the day, your sensor do effectively.

**Comment by LordMike** [comment]
Latest :dev applies measurement state_class to the measurement values, pH, orp etc.

I can't visually see anything within HASS, yet, .. so it'll be exciting to see what happens.. :P

**Comment by barto64** [comment]
You need to add the sensor to statistics-graph card and wait at least 2 hours as far as I recall to see the statistics of the sensors

**Comment by LordMike** [comment]
![image](https://user-images.githubusercontent.com/1027111/132996396-fc948083-e1e2-4456-b62c-15a3ef2ce934.png)

Well, it seems to have worked. :)

**Comment by barto64** [comment]
You are great Mike, well done Sir. Willing to download the next release. Great thanks

**Comment by barto64** [comment]
Hey @LordMike ,

Not really in a hurry, but do you have an ETA for the deployment in PRD of the modified sensors ?

Thanks,
@barto64

**Comment by LordMike** [comment]
If you're able to, you can always opt to run the `:dev` image. It will continuously be with the latest changes.

If not, then I can try to get a new version out soon.
