### ISSUE TITLE
(Question) Firmware update

### ISSUE THREAD

**Issue by ggggh** [LordMike/MBW.BlueRiiot2MQTT#72]
Just received a notice for a firmware update pending on my device, within the blueriiot app.  Have had very bad sigfox updates for the last few days, so wondering if it is a fix for that, but don't want to risk it if it has any chance of "breaking" the current functionality of this app.  Assuming it won't, as this app doesn't connect to the device itself, but wanted to ask you all in case anyone has already upgraded firmware and found any issues or improvements.

**Comment by LordMike** [comment]
I'm of the same understanding as you - the API I use is likely unchanged, and there shouldn't be any issues in updating the device.

But I am not aware of anyone updating their device - and I haven't done it myself (my pool hasn't been up this year).
