### ISSUE TITLE
Don't work in docker-compose

### ISSUE THREAD

**Issue by jeulogio** [LordMike/MBW.BlueRiiot2MQTT#75]
Hello,

First of all, thank you for your work. 

I have Mosquitto and Home Assistant with docker-compose. I try to run in docker-compose, but not works. This is the error:

[MqttNet.MqttClient] Error while connecting with serve.

My docker-compose configuration:

blueriiot2mqtt:
    image: lordmike/blueriiot2mqtt: latest
    environment:
         MQTT_Server: my server ip address
         BlueRiiot_Username: my username
         BlueRiiot_Password: my password

If i run with CLI using:

docker run -d -e MQTT__Server=myqueue.local -e BlueRiiot__Username=myuser -e BlueRiiot__Password=mypassword lordmike/blueriiot2mqtt:latest

works correctly. 

Any idea about the problem in docker-compose?

Thank yo

**Comment by jeulogio** [comment]
Hello,

I respect the tab in the docker-compose configuration.

Thanks

**Comment by LordMike** [comment]
Notice the double-underscore in the environment variables.
