### ISSUE TITLE
Add TLS support

### ISSUE THREAD

**Issue by gummigroda** [LordMike/MBW.BlueRiiot2MQTT#78]
Hi, and thanks for the great software.

How much labor would it be to add support for TLS in the MQTT connection?
(I'm no dev, and I can't seem to find where the connection to the MQTT server is being made in the code, any hints?)

**Comment by LordMike** [comment]
Missed this - it should be doable. It actually happens in another project of mine which wraps an MQTT client. The specific lines are here: https://github.com/LordMike/MBW.HassMQTT/blob/7af4e5bd36c1a0faa46cadff664b137fbd5bffb6/MBW.HassMQTT.CommonServices/CommonServicesExtensions.cs#L32-L35

Your TLS setup - is the certificate valid, or do you also need a method to bypass validation?

**Comment by gummigroda** [comment]
Great, thanks.

I'm using certificates from Let's Encrypt. So, the chain should be valid.

**Comment by LordMike** [comment]
I'll give it a go, but I have no way of testing. So we'll have to try it out :)

**Comment by LordMike** [comment]
I've pushed it. The configuration options are linked below. To run this you can pull the `:dev` docker image.

I think you just need to set:

* `MQTT__EnableTls` to `true`

Of course also setting the port if you run the TLS default (8883) - but you probably already know this. The other options can also be set with the `MQTT__` prefix.

https://github.com/LordMike/MBW.HassMQTT/blob/21937f455f4036742c3ebc09ade030696c08e41d/MBW.HassMQTT.CommonServices/CommonMqttConfiguration.cs#L22-L26

**Comment by gummigroda** [comment]
Okay, I've now enabled TLS and it works after I added ```MQTT__TlsProtocols: Tls12``` as my server don't allow deprecated protocols. Don't know what  the 'default' setting is using, but perhaps changing the default to 'Tls12' instead?

Thanks!

**Comment by LordMike** [comment]
The default is whatever the system uses by default. On windows this has changed over time towards more protocols.

I could set it to a mix of tls 1.0/1.1/1.2/1.3. Buut, when 1.4 or 2.0 drops, I’ll be behind. :/

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gummigroda** [comment]
I'm fine with keeping the default value.
Thanks for the support.
