### ISSUE TITLE
Response status code does not indicate success: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by bmgmo-iscteiulpt** [LordMike/MBW.BlueRiiot2MQTT#83]
Hello everyone!

After setting up the connection on a docker-compose file and starting the docker itself, it does not get measurements.
I put it in verbose mode, and the only thing I get are pings and from time to time this message :

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error)blueriiot2mqtt_1  | [2023-08-21 21:44:40+00:00 VRB] [MqttNet.MqttChannelAdapter] 

Does anyone know what might be happening? 

Thank you!

**Comment by LordMike** [comment]
That's odd - Blueriiot does have downtime now and then.. Is this still happening, and are your credentials correct?

**Comment by bmgmo-iscteiulpt** [comment]
Yes, it still happens. The credentials are from the android app correct? 
I have tried both with the app credentials and the website credentials but still nothing

**Comment by LordMike** [comment]
If you set the variable `Logging__MinimumLevel__Override__System.Net.Http.HttpClient.blueriiot` to Verbose or Information - you should get more details.

**Comment by bmgmo-iscteiulpt** [comment]
Well the previous message disappeared but now Im receiving messages on MQTT with just a payload "OK"  around twice per second, and nothing related to the sensors data
![image](https://github.com/LordMike/MBW.BlueRiiot2MQTT/assets/32707046/12b05b16-6f0a-43f0-8caa-4246a1fa1737)

**Comment by bmgmo-iscteiulpt** [comment]
I have pulled the docker-compose image again and this is what happens again :
![image](https://github.com/LordMike/MBW.BlueRiiot2MQTT/assets/32707046/3f2549b4-351e-41db-a388-6d0067518ac1)

**Comment by LordMike** [comment]
Ok - so we're inside the "LoginWithUsernamePassword", which means that BlueRiiots servers are refusing your username and password (rather, they're encountering something unexpected). I'm thinking that your credentials have something unexpected in them.

Could you try changing your password to something less complex, if you f.ex. have symbols. 

Could you also show your docker-compose configuration?

**Comment by bmgmo-iscteiulpt** [comment]
It worked! I guess those auto-generated passwords are too complicated xD

Thank you very much!
