### ISSUE TITLE
Is there a 0.15.1 release?

### ISSUE THREAD

**Issue by sddgit** [LordMike/MBW.BlueRiiot2MQTT#84]
HA is telling me there is an update for this add-on, V0.15.1. However, it's not mentioned in the releases on this repository. Should I be installing it, and what does it change?

**Comment by LordMike** [comment]
That is a good point. I make tags for releases, but I've previously promoted those tags to GH releases.. Maybe I should do this automatically.

0.15 is a general update with a bunch of HA MQTT specifics, while 0.15.1 adds TLS support for MQTT. You can upgrade without issues.

**Comment by LordMike** [comment]
Just a note. I've now ensured automatic releases on tags.

**Comment by sddgit** [comment]
Thank you for addressing this so quickly. I have updated to 0.15.2 successfully. I did notice, though, that HA said the changelog wasn’t available for the update. Should it be?
