### ISSUE TITLE
Extender needed

### ISSUE THREAD

**Issue by zebrahosting** [LordMike/MBW.BlueRiiot2MQTT#93]
Seeing this add-on for HA I ordered the blue connect plus for my mineral pool. Later I realized I live some where in the Asian jungle and might need the extender? Is this true?

**Comment by LordMike** [comment]
Well. I have no idea. Find a sigfox map for your area and see what the coverage is like. Sigfox also has a very large range, so it may work even in bad coverage.

But yea. If all fails you’ll need the WiFi extender.

Mike.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Zebra Hosting ***@***.***>
Sent: Friday, March 29, 2024 3:47:26 PM
To: LordMike/MBW.BlueRiiot2MQTT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LordMike/MBW.BlueRiiot2MQTT] Extender needed (Issue #93)


Seeing this add-on for HA I ordered the blue connect plus for my mineral pool. Later I realized I live some where in the Asian jungle and might need the extender? Is this true?

**Comment by zebrahosting** [comment]
Can't even connect a mobile phone there :-) Anyway ordered to extender to take it there.
Already bought and connected and your add-on works perfect!
Thanks very much for sharing your nice work!
